# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - 519assign1

on:
  push:
    branches: [ "master" ]
    paths:
      - "Node/WEB/**"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 519assign1
  AZURE_WEBAPP_PACKAGE_PATH: 'Node/WEB'
  FRONTEND_PACKAGE_PATH: 'Node/WEB/frontend'
  NODE_VERSION: '20.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: npm install

      - name: npm install for frontend
        working-directory: ${{ env.FRONTEND_PACKAGE_PATH }}
        run: |
          npm install
          npm run build
          rm -r public
          rm -r node_modules
          rm -r src

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .
  deploy:
    permissions: 
      contents: none
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D61BDB884FC74947BF04B57304EB7B7E }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
